name = "Untitled Pack"
author = "ACrazyCat"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0393a52087df10eee600ebcc6f0f856fd88dbc0251eb4e7d0592ac189a3e52d"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
