name = "Untitled Pack"
author = "ACrazyCat"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32af7a397b6f407da6e2875b227df03fb2016e7eeacd3ab9715b9eb93ce9a199"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
