name = "Untitled Pack"
author = "ACrazyCat"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "020813aba7d09c5afa452287e44bfc78a8f3280777839c0cf9199a7712e82855"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
